# Release workflow using reusable syster-pipelines workflow
# See: https://github.com/jade-codes/syster-pipelines

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'  # Pre-releases like v0.1.0-alpha

permissions:
  contents: write
  id-token: write

jobs:
  npm-release:
    uses: jade-codes/syster-pipelines/.github/workflows/npm-release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
